sudo: required
dist: trusty
language: generic

env:
  global:
    - UPSTREAM_WORKSPACE=https://raw.githubusercontent.com/kuka-isir/rtt_lwr/rtt_lwr-2.0/lwr_utils/config/orocos_toolchain-2.9.rosinstall
    - ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - BEFORE_SCRIPT="cd /root/catkin_ws/src/orocos_toolchain/orogen && git remote add ahoarau https://github.com/ahoarau/orogen && git fetch ahoarau && git checkout ahoarau/fix-catkin-dep && source /opt/ros/$ROS_DISTRO/setup.bash"
  matrix:
    - ROS_DISTRO="indigo"
    - ROS_DISTRO="jade"
    - ROS_DISTRO="kinetic"
    - ROS_DISTRO="lunar"

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - source .ci_config/travis.sh

