sudo: required
dist: trusty
language: generic

env:
  global:
    - UPSTREAM_WORKSPACE=https://raw.githubusercontent.com/kuka-isir/rtt_lwr/rtt_lwr-2.0/lwr_utils/config/orocos_toolchain-2.9.rosinstall
    - ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    # rosdep fix , discussed here https://github.com/orocos-toolchain/orogen/issues/88
    - BEFORE_SCRIPT="rm -rf /root/catkin_ws/src/orocos_toolchain/orogen/manifest.xml"
    - NO_BUILD_TESTS=true
    - NO_TEST_INSTALL=true
    - CATKIN_PARALLEL_JOBS='-p1'
    - ROS_PARALLEL_JOBS='-j1'
  matrix:
    - ROS_DISTRO="indigo"
    - ROS_DISTRO="jade"
    - ROS_DISTRO="kinetic"
    - ROS_DISTRO="lunar"

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - source .ci_config/travis.sh

