sudo: required
dist: trusty
language: generic

branches:
  only:
  - master

env:
  global:
    - UPSTREAM_WORKSPACE=https://raw.githubusercontent.com/kuka-isir/rtt_lwr/rtt_lwr-2.0/lwr_utils/config/orocos_toolchain-2.9.rosinstall
    - ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    # rosdep fix , discussed here https://github.com/orocos-toolchain/orogen/issues/88
    - BEFORE_SCRIPT="rm /root/catkin_ws/src/orocos_toolchain/orogen/manifest.xml"
    - NOT_TEST_BUILD=true
    - CATKIN_PARALLEL_JOBS="-p3 --cmake-args -DCMAKE_BUILD_TYPE=Release -DENABLE_CORBA=ON -DCORBA_IMPLEMENTATION=OMNIORB --"
    - ROS_PARALLEL_JOBS="-j3"
    - DOCKER_RUN_OPTS="-v $HOME/install:/root/catkin_ws/install"
    
  matrix:
    - ROS_DISTRO="indigo"
    - ROS_DISTRO="jade"
    - ROS_DISTRO="kinetic"
    - ROS_DISTRO="lunar"

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - mkdir $HOME/install
  - source .ci_config/travis.sh
  - tar -czf $HOME/orocos_toolchain-2.9-$ROS_DISTRO-release.tar.gz -C $HOME/install/ .

after_success:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=build-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
  - echo -n $GIT_TAG > public/version
  - git commit -m "Build VERSION number" public/version
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push --quiet https://$API_TOKEN@github.com/ahoarau/orocos_toolchain-build $GIT_TAG > /dev/null 2>&1

deploy:
  provider: releases
  api-key: 
      secure: $API_TOKEN
  file: $HOME/orocos_toolchain-2.9-$ROS_DISTRO-release.tar.gz
  skip_cleanup: true
  on:
    branch: master

